services:
    olstudio-postgresql:
        container_name: olstudio-postgresql
        image: postgis/postgis:16-3.4
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - olstudio-postgresql-data:/var/lib/postgresql/data
volumes:
    olstudio-postgresql-data: